name: /Users/petercrady/StudioProjects/fife_lab/server/fife_lab_env
channels:
  - defaults
  - conda-forge
dependencies:
  - annotated-types=0.6.0=py313hca03da5_0
  - anyio=4.7.0=py313hca03da5_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - click=8.1.8=py313hca03da5_0
  - expat=2.7.1=h313beb8_0
  - fastapi=0.112.2=py313hca03da5_0
  - h11=0.14.0=py313hca03da5_0
  - idna=3.7=py313hca03da5_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.4=hca03da5_1
  - libmpdec=4.0.0=h80987f9_0
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.16=h02f6b3c_0
  - pip=25.0=py313hca03da5_0
  - pydantic=2.10.3=py313hca03da5_0
  - pydantic-core=2.27.1=py313h2aea54e_0
  - python=3.13.2=h4862095_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.2=h1a28f6b_0
  - setuptools=75.8.0=py313hca03da5_0
  - sniffio=1.3.0=py313hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - starlette=0.38.2=py313hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - typing-extensions=4.12.2=py313hca03da5_0
  - typing_extensions=4.12.2=py313hca03da5_0
  - tzdata=2025a=h04d1e81_0
  - uvicorn=0.32.1=py313hca03da5_0
  - websockets=10.4=py313h80987f9_2
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.2.13=h18a0788_1
prefix: /Users/petercrady/StudioProjects/fife_lab/server/fife_lab_env
